### ISSUE TITLE
Create basic demo R-shiny app

### ISSUE THREAD

**Issue by QuentinDaveau** [QuentinDaveau/Whack_A_Mole_RShiny#1]
It is required to have a "demo" shiny app showcasing its applications, whith graphics, interactions, and samples from whack-a-mole games. The deadline is friday 29 november.

**Comment by QuentinDaveau** [comment]
Things to display for the demo:

- [ ] Multiples tabs
- [ ] Participant selection
- [ ] Hit/Miss/Average heatmaps
- [ ] Basic info (average hit time, hit/miss ratio, test duration, speed, modifiers)
- [ ] Test selection, average of tests

**Comment by QuentinDaveau** [comment]
To do: generate a set of correct datas under the participant ID 42 to use for the demo.

**Comment by QuentinDaveau** [comment]
Added the heatmap, participant selection, test selection, difficulty selection:

![shiny_heatmap](https://user-images.githubusercontent.com/45624296/69337365-f7ae2400-0c60-11ea-8823-aac0eca3993d.gif)

**Comment by bastianilso** [comment]
@QuentinDaveau great, really nice.

Here are my suggestions for dropdowns:
- Dropdown 1 selects a date (with an option for averaging across all dates).
- Dropdown 2 selects the participant (with an option for all participants).
- Dropdown 3 chooses among any results we get with that selection. Name the tests based on the exact time (hh:mm) which they were run. Keep also an option for averaging across all tests which is default.
- Add a section underneath, which summarizes the properties of the currently selected test(s), fx:

> Participant 1
> Test 0
> Duration: 2 minutes
> 
> Modifiers:
> Eye patch left
> Speed slow

**Comment by QuentinDaveau** [comment]
Maybe I can try to add some sort of "test timeline", which would display all events for a given test on a timeline, with different colors for event types and all. That would be pretty neat but would require quite a bit of work. I'll try to add it if I have enough time.
