### ISSUE TITLE
Preparation for VR Workshop Friday

### ISSUE THREAD

**Issue by bastianilso** [QuentinDaveau/Whack_A_Mole_RShiny#2]
I and Hendrik was trying the Whack-A-Mole VR R-Shiny App, in preparation for the workshop on Friday. 🚗  We have a few minor tweaks that would make it easier to understand what is going on. I know this app is work-in-progress  - this issue is just to highlight the most prominent things we would like to get ready by then:

![image](https://user-images.githubusercontent.com/3967945/69732168-6e4c9500-112b-11ea-9a74-13d3767ea312.png)

- [ ] The "Precision" graph, uses two dimensions "wt" and "mpg" - make sure that the dimensions has legible names that makes sense.
- [ ] The name "Precision" does not make it clear, what the precision is about. Is it the precision of the player? Then maybe we can call it "Shooting Precision".
- [ ] We may want to place upper and lower limits onto the graph - so the data doesnt become disproportionate.
- [ ] We need human-understandable names for what the colors mean in the heatmap. I would suggest sticking to colors from green to red, to keep make the colors intuitive to guess in terms of meaning (good, bad).

**Comment by QuentinDaveau** [comment]
@bastianilso the "precision" graph is a fake one purely to test the layout, for now it doesn't mean anything. However the heatmap is a true one, but it needs more data to be relevant. I'll update the heatmap colors.

**Comment by QuentinDaveau** [comment]
I can try to generate a timeline graph which would replace the precision one, but I'm not sure I'll have the time to do it for friday.

**Comment by bastianilso** [comment]
@QuentinDaveau OK. For the Friday workshop, we mostly need graphs that show real data. 😃 
As for getting more data for the heatmap, I think it might be worthwhile for us to let a few people play Whack-a-Mole tomorrow morning. Have a new person play it everytime - so not just the same participant.

We can do this as part of the dry-run of the workshop tomorrow.

**Comment by bastianilso** [comment]
@QuentinDaveau no need to stress about it - we can just leave it out for now. we would rather show people one legible heatmap graph than many graphs that still needs more work. 👍
